name: publish

on: push

jobs:
  publish:
    - name: Invoke workflow in ymath-io/ymath.io
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: cd
        repo: ymath-io/ymath.io
        token: ${{ secrets.PERSONAL_TOKEN }}

